config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "profile", to: 'pages#profile'
  get "secret", to: 'pages#secret'
  get "queen", to: 'pages#queen'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :gardens do
    resources :bookings, except: [:destroy]
    resources :reviews, only: [:new, :edit, :create, :update]
  end
  resources :reviews, only: [:destroy]
  
  root to: 'pages#home'
end

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<% unless current_page?(secret_path) %> 
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://res.cloudinary.com/duxof8o3p/image/upload/v1628185793/logo_nbqcee.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if user_signed_in? %>

        <li class="nav-item m-3">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link"  %>
        </li>

          <li class="nav-item ">
              <%= link_to profile_path do %>          
                <% if user_signed_in? && current_user.photo.attached? %>
                  <div class="avatar-profile" style = "background-image: url(<%= current_user.photo.service_url %>)"></div>
                <% else %>
                    <div class="avatar-profile" style = "background-image: url(https://res.cloudinary.com/duxof8o3p/image/upload/v1628204156/orcnli5i1wu4j400yrh7gn3xnz40.jpg)" ></div>
              <% end %>
            <% end %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>