config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "profile", to: 'pages#profile'
  get "secret", to: 'pages#secret'
  get "queen", to: 'pages#queen'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :gardens do
    resources :bookings, except: [:destroy]
    resources :reviews, only: [:new, :edit, :create, :update]
  end
  resources :reviews, only: [:destroy]
  
  root to: 'pages#home'
end

app/views/pages/home.html.erb
<div class="blob">
  <svg xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 310 350">
  <path d="M156.4,339.5c31.8-2.5,59.4-26.8,80.2-48.5c28.3-29.5,40.5-47,56.1-85.1c14-34.3,20.7-75.6,2.3-111  c-18.1-34.8-55.7-58-90.4-72.3c-11.7-4.8-24.1-8.8-36.8-11.5l-0.9-0.9l-0.6,0.6c-27.7-5.8-56.6-6-82.4,3c-38.8,13.6-64,48.8-66.8,90.3c-3,43.9,17.8,88.3,33.7,128.8c5.3,13.5,10.4,27.1,14.9,40.9C77.5,309.9,111,343,156.4,339.5z"/>
    <linearGradient id="header-shape-gradient" x2="0.35" y2="1">
        <stop offset="0%" stop-color="var(--color-stop)" />
        <stop offset="30%" stop-color="var(--color-stop)" />
        <stop offset="100%" stop-color="var(--color-bot)" />
    </linearGradient>
  </svg>
</div>
<div class="main_container">
  <div class="main_left">
    <h1>ANTS IN</h1>
    <h2>YOUR PANTS</h2>
    <div class="main_buttons">
      <%= link_to "Rent a Garden", gardens_path, class: "main_rent" %>
      <%= link_to "List a Garden", new_garden_path, class: "main_list" %>
    </div>
    <p>Go to the most beautiful gardens available.</p>
  </div>
  <div class="main_right">
    <%= image_tag "https://res.cloudinary.com/duxof8o3p/image/upload/v1628185794/pixelart_iokrjw.png" %>
  </div>
</div>

<div class="footer">
  <p>Follow us:</p>
  <div class="icons">
    <i class="fab fa-github"></i>
    <i class="fab fa-linkedin"></i>
    <i class="fas fa-envelope"></i>
  </div>

</div>

app/views/pages/profile.html.erb
<div class="blob">
  <svg xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 310 350">
  <path d="M156.4,339.5c31.8-2.5,59.4-26.8,80.2-48.5c28.3-29.5,40.5-47,56.1-85.1c14-34.3,20.7-75.6,2.3-111  c-18.1-34.8-55.7-58-90.4-72.3c-11.7-4.8-24.1-8.8-36.8-11.5l-0.9-0.9l-0.6,0.6c-27.7-5.8-56.6-6-82.4,3c-38.8,13.6-64,48.8-66.8,90.3c-3,43.9,17.8,88.3,33.7,128.8c5.3,13.5,10.4,27.1,14.9,40.9C77.5,309.9,111,343,156.4,339.5z"/>
    <linearGradient id="header-shape-gradient" x2="0.35" y2="1">
        <stop offset="0%" stop-color="var(--color-stop)" />
        <stop offset="30%" stop-color="var(--color-stop)" />
        <stop offset="100%" stop-color="var(--color-bot)" />
    </linearGradient>
  </svg>
</div>

  <div class = " wrapper-profile">
    <div class = "profile-container">
      <div class="profile-titles"> 
        <h2 class="my-stuff">My bookings</h2>
      </div>
      <% if current_user.bookings.nil? %>
        <p>No bookings mades yet</p>
      <% else %>
        <% current_user.bookings.reverse.each do |booking| %>
        <div class="cards-profile">
            <div>
              <% if !booking.garden.photos.attached? %>
                <%= image_tag "https://res.cloudinary.com/duxof8o3p/image/upload/v1628185794/pixelart_iokrjw.png", width: 400, height: 300, crop: :fill  %>
              <% else %>
                <%= cl_image_tag booking.garden.photos[0].key, width: 400, height: 300, crop: :fill %>
              <% end %>
            </div>
            <div class = "card-booking-text">
              <h2> <%= link_to booking.garden.title, garden_booking_path(booking.garden, booking)  %></h2> 
              <p> <%= booking.garden.address %></p>
              <p>From <b> <%=  booking.start_date.strftime('%a %d-%m-%y')%></b> to <b><%= booking.end_date.strftime('%a %d-%m-%y') %><b></p>
            </div>
        </div>
        <% end %> 
      <% end %> 
    </div> 
    <div class = "profile-container">
      <div class="profile-titles"> 
        <h2 class="my-stuff">My gardens</h2>
      </div>
        <% if current_user.gardens.nil? %>
          <p>No garden </p>
        <% else %>
          <% current_user.gardens.reverse.each do |garden| %>
          <div class="cards-profile">
              <div>
                <% if !garden.photos.attached? %>
                  <%= image_tag "https://res.cloudinary.com/duxof8o3p/image/upload/v1628185794/pixelart_iokrjw.png", width: 400, height: 300, crop: :fill  %>
                <% else %>
                  <%= cl_image_tag garden.photos[0].key, width: 400, height: 300, crop: :fill %>
                <% end %>
              </div>
              <div class = " card-booking-text ">
                <h2> <%= link_to garden.title, garden_path(garden) %></h2> 
                <p> <%= garden.address %></p>
              </div>
          </div>
          <% end %> 
        <% end %> 
    </div>
  </div>

app/views/pages/queen.erb
<div class="blob">
  <svg xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 310 350">
  <path d="M156.4,339.5c31.8-2.5,59.4-26.8,80.2-48.5c28.3-29.5,40.5-47,56.1-85.1c14-34.3,20.7-75.6,2.3-111  c-18.1-34.8-55.7-58-90.4-72.3c-11.7-4.8-24.1-8.8-36.8-11.5l-0.9-0.9l-0.6,0.6c-27.7-5.8-56.6-6-82.4,3c-38.8,13.6-64,48.8-66.8,90.3c-3,43.9,17.8,88.3,33.7,128.8c5.3,13.5,10.4,27.1,14.9,40.9C77.5,309.9,111,343,156.4,339.5z"/>
    <linearGradient id="header-shape-gradient" x2="0.35" y2="1">
        <stop offset="0%" stop-color="var(--color-stop)" />
        <stop offset="30%" stop-color="var(--color-stop)" />
        <stop offset="100%" stop-color="var(--color-bot)" />
    </linearGradient>
  </svg>
</div>

<div class="container queen" >
  <%= cl_image_tag "https://res.cloudinary.com/duxof8o3p/image/upload/v1628757114/gardens/queen-elizabeth-i3i_w6pslt.jpg", width: 1000, crop: :fill %>
</div>

app/views/pages/secret.html.erb
<meta HTTP-EQUIV="REFRESH" content="40; url= queen">


<a data-toggle="modal" data-target="#myModal"></button>
  <%= cl_image_tag("https://res.cloudinary.com/duxof8o3p/image/upload/v1628632987/gardens/secret_g9c3cn.png", crop: :fill) %>
</a>


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      </div>
      <div class="modal-body">
          <iframe src="https://hackertyper.net" width="470" height="600" frameborder="2" allowtransparency="false"></iframe>  
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>
<!-- /.modal -->