config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "profile", to: 'pages#profile'
  get "secret", to: 'pages#secret'
  get "queen", to: 'pages#queen'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :gardens do
    resources :bookings, except: [:destroy]
    resources :reviews, only: [:new, :edit, :create, :update]
  end
  resources :reviews, only: [:destroy]
  
  root to: 'pages#home'
end

app/models/garden.rb
class Garden < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :reviews, dependent: :destroy
  has_many_attached :photos
  validates :title, :address, :price, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  
  include PgSearch::Model
  pg_search_scope :search_by_address,
    against: [ :address ],
    using: {
      tsearch: { prefix: true } 
    }

end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
    skip_before_action :authenticate_user!, only: [:index, :show]
    before_action :set_user
    before_action :set_garden, only: [:show, :edit, :update, :destroy]

    def index
      if params[:query].present?
        sql_query = "
        gardens.address @@ :query
        "
        @gardens = Garden.where(sql_query, query: "%#{params[:query]}%")
      else
        @gardens = Garden.all
      end
      @markers = @gardens.geocoded.map do |garden|
        {
          lat: garden.latitude,
          lng: garden.longitude,
          info_window: render_to_string(partial: "info_window", locals: { garden: garden })
        }
      end
    end

    def show
      @review = Review.new
    end

    def edit
    end

    def new
      @garden = Garden.new
    end

    def create
      @garden = Garden.new(strong_params)
      @garden.user = @user
      if @garden.save
        redirect_to garden_path(@garden)
      else
        render :new
      end
    end

    def destroy
      @garden.delete
      redirect_to gardens_path
    end

    private

    def strong_params
      params.require(:garden).permit(:title, :address, :price, { photos: [] }, :description) #order matters if you do not use {} for hash
    end

    def set_user
      if user_signed_in?
        @user = current_user
      end
    end

    def set_garden
      @garden = Garden.find(params[:id])
    end
end

app/views/gardens/_form.html.erb
<%= simple_form_for :garden do |f| %>
  <%= f.input :title %>
  <%= f.input :address, class: "garden_address" %>
  <%= f.input :price %>
  <%= f.submit "Add a Garden", class: "btn btn-primary" %>
<% end %>

app/views/gardens/_info_window.html.erb
<h3><%= garden.title %></h6>
<h6><%= garden.address %></h6>

app/views/gardens/_review.html.erb
<%= simple_form_for [ @garden, @review ] do |f| %>
  <%= f.input :rating, input_html: { style: "border-radius: 20px;" } %>
  <%= f.input :content, input_html: { style: "border-radius: 20px;" } %>
  <%= f.submit "Add review", class: "btn btn-flat" %>
<% end %>

app/views/gardens/index.html.erb
<div class="blob">
  <svg xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 310 350">
  <path d="M156.4,339.5c31.8-2.5,59.4-26.8,80.2-48.5c28.3-29.5,40.5-47,56.1-85.1c14-34.3,20.7-75.6,2.3-111  c-18.1-34.8-55.7-58-90.4-72.3c-11.7-4.8-24.1-8.8-36.8-11.5l-0.9-0.9l-0.6,0.6c-27.7-5.8-56.6-6-82.4,3c-38.8,13.6-64,48.8-66.8,90.3c-3,43.9,17.8,88.3,33.7,128.8c5.3,13.5,10.4,27.1,14.9,40.9C77.5,309.9,111,343,156.4,339.5z"/>
    <linearGradient id="header-shape-gradient" x2="0.35" y2="1">
        <stop offset="0%" stop-color="var(--color-stop)" />
        <stop offset="30%" stop-color="var(--color-stop)" />
        <stop offset="100%" stop-color="var(--color-bot)" />
    </linearGradient>
  </svg>
</div>
<div class="container">
  <div class="d-flex">
    <div class="search search-bar w-100 ">
      <%= form_tag gardens_path, method: :get do %>
      <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "search by address",
      style: "border-radius: 20px;"
      %> 
    </div>
    <div>
      <%= submit_tag "Search", class: "btn btn-primary search-button" %>
      <% end %>
    </div>
  </div>
</div>

<div class="main-grid">
  <div class="left-grid">
    <div class="scrolling">
      <% @gardens.each do |garden| %>
        <div class="card-garden" data-toggle="modal" data-target="#myModal_<%= garden.id %>">
          <div class="modal fade" id="myModal_<%= garden.id %>" tabindex="-1" role="dialog" aria-labelledby="popupLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content popup">
                <div class="modal-header">
                  <h3 class="modal-title" id="popupLabel"><%= garden.title %></h3>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <h4><%= garden.address  %></h3>
                  <p> <%= garden.description %> </p>
                  <p><i class="fab fa-btc bit"></i> <span class="garden_price_info"><%= garden.price%></span></p>  
                </div>
                <div class="modal-footer">
                  <%= link_to "See Garden",  garden_path(garden), class: "light-green-button" %>
                  <%= link_to "See bookings",  garden_bookings_path(garden), class: "light-green-button" %>
                </div>
              </div>
            </div>
          </div>
            <%# if garden.photo.key is present then show below %>
            <% if garden.photos.attached? %>
              <%= cl_image_tag garden.photos[0].key, width: 400, height: 210, crop: :fill   %>
            <% else %>
              <%= image_tag "https://res.cloudinary.com/duxof8o3p/image/upload/v1628185794/pixelart_iokrjw.png", width: 400, height: 210, crop: :fill  %>
              <%# else give a cl_image for a stock image below  %>
            <% end %>
            <div class="card-garden-infos">
              <div>
                <h2><%= link_to garden.title.truncate(39, separator: ' '), garden_path(garden) %></h2>
                <p><%= garden.address.truncate(35, separator: ' ') %></p>
                <%# <p><%= link_to "See bookings", garden_bookings_path(garden) %></p>
              <div class="details">
                <span class="badge badge-pill badge-info badges" > <%= pluralize garden.bookings.count, "Booking" %> </span>
                <span class="badge badge-pill badge-info badges" style = "margin-left: -75px"> <%= pluralize garden.reviews.count, "Review" %> </span>
               
                  <div class= "price">
                    <%= garden.price %> 
                    <i class="fab fa-btc bit"></i> /day
                  </div>
              </div>
              </div>
            </div>
        </div>
      <% end %>
    </div>
  </div>
  <div id="map" class="map"
      style="width: 30%; height: 641px; margin-left: 25px"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div> 
</div>

app/views/gardens/new.html.erb
<div class="blob">
  <svg xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 310 350">
  <path d="M156.4,339.5c31.8-2.5,59.4-26.8,80.2-48.5c28.3-29.5,40.5-47,56.1-85.1c14-34.3,20.7-75.6,2.3-111  c-18.1-34.8-55.7-58-90.4-72.3c-11.7-4.8-24.1-8.8-36.8-11.5l-0.9-0.9l-0.6,0.6c-27.7-5.8-56.6-6-82.4,3c-38.8,13.6-64,48.8-66.8,90.3c-3,43.9,17.8,88.3,33.7,128.8c5.3,13.5,10.4,27.1,14.9,40.9C77.5,309.9,111,343,156.4,339.5z"/>
    <linearGradient id="header-shape-gradient" x2="0.35" y2="1">
        <stop offset="0%" stop-color="var(--color-stop)" />
        <stop offset="30%" stop-color="var(--color-stop)" />
        <stop offset="100%" stop-color="var(--color-bot)" />
    </linearGradient>
  </svg>
</div>
<div class="container card-form">
<div class="row">
<div class="col-6">
<%= simple_form_for @garden do |f| %>
  <%= f.input :title,  input_html: { style: "border-radius: 20px;" } %>
  <%= f.input :address, class: "garden_address", input_html: { style: "border-radius: 20px;" } %>
  <%= f.input :price, input_html: { style: "border-radius: 20px;" } %>
  <%= f.input :description, input_html: { style: "border-radius: 20px;" } %>
  <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  <%= f.submit "Add a Garden", class: "search-button", style: "margin-left: 0px;" %>
<% end %>
</div>
</div>
</div>

app/views/gardens/show.html.erb
<div class="blob">
  <svg xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 310 350">
  <path d="M156.4,339.5c31.8-2.5,59.4-26.8,80.2-48.5c28.3-29.5,40.5-47,56.1-85.1c14-34.3,20.7-75.6,2.3-111  c-18.1-34.8-55.7-58-90.4-72.3c-11.7-4.8-24.1-8.8-36.8-11.5l-0.9-0.9l-0.6,0.6c-27.7-5.8-56.6-6-82.4,3c-38.8,13.6-64,48.8-66.8,90.3c-3,43.9,17.8,88.3,33.7,128.8c5.3,13.5,10.4,27.1,14.9,40.9C77.5,309.9,111,343,156.4,339.5z"/>
    <linearGradient id="header-shape-gradient" x2="0.35" y2="1">
        <stop offset="0%" stop-color="var(--color-stop)" />
        <stop offset="30%" stop-color="var(--color-stop)" />
        <stop offset="100%" stop-color="var(--color-bot)" />
    </linearGradient>
  </svg>
</div>
 
<div class="wrapper-show">
  <div class="garden-wrapper">
    <% if !@garden.photos.attached? %>
      <%= image_tag "https://res.cloudinary.com/duxof8o3p/image/upload/v1628185794/pixelart_iokrjw.png", class:"d-block garden-img w-100"  %>

    <% elsif @garden.photos.size == 1 %>
      <img class="d-block garden-img w-100" src="<%= cl_image_path @garden.photos.first.key %>" alt="photo" >

    <% elsif @garden.photos.size > 1 %>
      <div id="carouselExampleIndicators" class="carousel slide">

        <div class="carousel-inner">
          <% @garden.photos.each_with_index do |photo, index| %>
            <div class="carousel-item <%= "active" if index.zero? %>">
                <img class="d-block garden-img w-100" src="<%= cl_image_path photo.key %>" alt="<%= index.ordinalize %> image">
            </div>
          <% end %>
        </div>
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>

          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
    <% end %>
  </div>

  <div class="garden-info">
    <div class="garden-text">
      <h1><%= @garden.title %></h1>
      <h2><%=@garden.address  %></h2>
      <p> <%=@garden.description %> </p>
    </div>
    <div class="garden-price-btn">
      <p><i class="fab fa-btc bit"></i> <span class="garden_price_info"><%= @garden.price%></span></p>
    </div>
      <div>
      <% if current_user == @garden.user %>
        <div class="main_buttons">
          <%= link_to "All Gardens", gardens_path, class: "light-green-button" %>
          <%= link_to "Profile", profile_path, class: "light-green-button" %>
        </div>
      <% else %>
       <div class="main_buttons">
          <%= link_to "book now", new_garden_booking_path(@garden, @booking), class: "light-green-button" %>
          <%= link_to "go back to gardens", gardens_path, class: "light-green-button" %>
        </div>
      <% end %>         
      </div>
  </div>


    <div class="reviews">
        <div class="display-reviews">
          <% if @garden.reviews.empty? %>
            <p>Be the first to leave a review!</p>
          <% else %>
            <% @sum = 0 %>
            <% @garden.reviews.each do |review| %>
              <% @sum += review.rating %>
            <% end %>
            <% @garden_rating = @sum.fdiv(@garden.reviews.length) %>
            
            <% @garden.reviews.each do |review| %>
            <p><% review.rating.times do %>
              💚
              <% end %>
            </p>
            <p><%= review.content %></p>
            <% if review.user == current_user %>
              <%= link_to review_path(review), method: :delete,
                  data: { confirm: "Are you sure?" } do %>
              <p class="text-success"><i class="fas fa-trash"></i> Delete</p>
              <% end %>
            <% end %>
            <% unless review == @garden.reviews.last %>
              <hr>
            <% end %>
            <% end %>
          <% end %>
        </div>
        <div class="new-review">
          <%= render "review", garden: @garden, review: @review %>
        </div>
    </div>
 </div>